### ISSUE TITLE
[self-host] No such namespace env-config

### ISSUE THREAD

**Issue by arichiardi** [binaryage/cljs-oops#8]
Hello Darwin!

I was trying to make `cljs-oops` work in `lumo` (self-host cljs) and I have run across the following:
```
#error {:message No such namespace: env-config.core, could not locate env_config/core.cljs, env_config/core.cljc, or Closure namespace "env-config.core" in file oops/config.clj, :data {:tag :cljs/analysis-error}}
``` 

I have two questions:

1) why is the library including a namespace for fetching environment variables? Is it a feature (in which case I can try to document it in the README) ?
2) Probably the macros are not self-host compatible, would you be open to some sort of refactoring patch that will fix this?

Thanks, as usual awesome work (I have used this successfully with cljs on jvm) !

**Comment by darwin** [comment]
Hi Andrea,

The error looks like you don't have [env-config](https://github.com/binaryage/env-config) library on "classpath". I assume normal leiningen project.clj dependecies don't work in self-hosted mode and you have to specify dependencies in another way.

1. cljs-oops code generation [can be configured](https://github.com/binaryage/cljs-oops#tailor-oops-behaviour) via compiler [options](https://github.com/binaryage/cljs-oops/blob/master/src/lib/oops/defaults.clj) and [since 0.5.2](https://github.com/binaryage/cljs-oops/releases/tag/v0.5.2) those options can be overridden via environmental variables.

2. the macros weren't designed with self-host in mind, but I don't think there are many places where I would assume JVM under the hood. env-config library seems to be JVM agnostic. And in cljs-oops,  for example [here](https://github.com/binaryage/cljs-oops/blob/master/src/lib/oops/config.clj#L32-L35) your would have to return an empty map or retrieve oops compiler options some other way suitable for node.js.

I'm open for patches.

**Comment by darwin** [comment]
Bump! @arichiardi are you going to do something about this one?

**Comment by arichiardi** [comment]
Eventually I would like to of course, time will tell I guess 😀😀...

**Comment by darwin** [comment]
I'm going to close this one. Feel free to reopen if you have a specific actionable plan.
